account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.login_view, name='login'),
    path('logout/', views.login_view, name='logout'),  # Use the custom logout view
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(extra_context={'next_page': '/home'}), name='password_reset_complete'),
    path('profile/',views.user_profile, name='profile'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('delete-account/', views.delete_account, name='delete_account'),
   
    
]

admin_panel/urls.py
from django.urls import path
from . import views

app_name = 'admin_panel'

urlpatterns = [
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    path('user_profile/', views.user_profile_view, name='user_profile'),
    path('delete_profile/<int:profile_id>/', views.delete_profile, name='delete_profile'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('add_user/', views.add_user, name='add_user'),
    path('categories/', views.category_list, name='category_list'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('update_category/<int:category_id>/', views.update_category, name='update_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('featured-projects/', views.featured_projects, name='featured_projects'),
    path('delete-featured-project/<int:project_id>/', views.delete_featured_project, name='delete_featured_project'),
    path('featured-projects/<int:project_id>/update/', views.update_featured_project, name='update_featured_project'),
    path('add_featured_project/', views.add_featured_project, name='add_featured_project'),
    path('comments/', views.comment_list, name='comment'),
    path('comments/add/', views.add_comment, name='addcomment'),
    path('comments/<int:pk>/update/', views.update_comment, name='updatecomment'),
    path('add_donation/', views.add_donation, name='add_donation'),
    path('update_donation/<int:donation_id>/', views.update_donation, name='update_donation'),
    path('list_donations/', views.list_donations, name='donations'),
    path('add_reply/', views.add_reply, name='add_reply'),
    path('update_reply/<int:reply_id>/', views.update_reply, name='update_reply'),
    path('list_replies/', views.list_replies, name='replies'),
    path('show-tags/', views.show_added_tags, name='show_added_tags'),
    path('add-tag/',views.add_tag, name='add_tag'),
    path('update-tag/<int:tag_id>/',views.update_tag, name='update_tag'),
    path('delete-tag/<int:tag_id>/', views.delete_tag, name='delete_tag'),
    path('rate-project/', views.rate_project, name='rate_project'),
    path('show-rate/', views.show_rate, name='show_rate'),
    path('update-rating/<int:rating_id>/', views.update_rating, name='update_rating'),
    path('delete-rating/<int:rating_id>/', views.delete_rating, name='delete_rating'),
    path('add-report/', views.add_report, name='add_report'),
    path('show-reports/', views.show_reports, name='show_reports'),
    path('update_report/<int:report_id>/', views.update_report, name='update_report'),
    path('delete_report/<int:report_id>/', views.delete_report, name='delete_report'),
    path('projects/', views.project_list_view, name='project'), 
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('update_project/<int:project_id>/', views.update_project, name='update_project'),
    path('add_project/', views.add_project, name='add_project'),
    path('cancellation/list/', views.cancellation_list, name='cancellation_list'),
    path('update_cancellation/<int:cancellation_id>/', views.update_cancellation, name='update_cancellation'),
    path('cancellation/create/', views.create_cancellation, name='create_cancellation'),
    path('cancellation/<int:cancellation_id>/delete/', views.delete_cancellation, name='delete_cancellation'),
    path('project/pictures/', views.project_picture_list, name='project_picture_list'),
    path('project/pictures/add/', views.add_project_picture, name='add_project_picture'),
    path('project/pictures/<int:picture_id>/update/', views.update_project_picture, name='update_project_picture'),
    path('project/pictures/<int:picture_id>/delete/', views.delete_project_picture, name='delete_project_picture'),

   
]

charityProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('project/', include('project.urls')), 
    path('admin_panel/', include('admin_panel.urls')),
    path('userPayment/', include('userPayment.urls')), 
    path('', include('paypal.standard.ipn.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_panel/models.py
from django.db import models

# Create your models here.

project/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
#########################  UserProfile  ################################

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_phone = models.CharField(max_length=15)  
    profile_picture = models.ImageField(upload_to='profile_pictures/%Y/%m/%d', null=True, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    facebook_profile = models.URLField(null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)

    @classmethod
    def count_objects(cls):
        return cls.objects.count()
    
    def __str__(self):
        return self.user.username

#######################   Category  ################################

class Category(models.Model):
    name = models.CharField(max_length=100)

    @classmethod
    def count_objects(cls):
        return cls.objects.count()
    
    def __str__(self):
        return self.name

##########################   Project #######################################################
class Project(models.Model):
    title = models.CharField(max_length=255)
    details = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    total_target = models.DecimalField(max_digits=10, decimal_places=2)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    is_cancelled = models.BooleanField(default=False)
    country = models.CharField(max_length=100, null=True, blank=True) 

    def total_donations(self):
        return self.donation_set.aggregate(models.Sum('amount'))['amount__sum'] or 0

    def total_ratings(self):
        return self.rating_set.aggregate(models.Sum('rating'))['rating__sum'] or 0
    
  
    def pictures(self):
       
        picture = self.projectpicture_set.first()
        if picture:
            return picture.image.url
        else:
            return None   

    def remaining_time(self):
        now = timezone.now()
        time_left = self.end_time - now
        days = time_left.days
        hours, remainder = divmod(time_left.seconds, 3600)
        months = days // 30
        remaining_days = days % 30
        remaining_time_msg = f"{months} months, {remaining_days} days, {hours} hours"
        return remaining_time_msg

    @staticmethod
    def top_rated_projects():
        top_projects = Project.objects.annotate(total_rating=models.Sum('rating__rating')).order_by('-total_rating')
        return top_projects
    

    @property
    def progress_percentage(self):
        if self.total_target > 0:
            return (self.total_donations() / self.total_target) * 100
        else:
            return 0 
        

    @classmethod
    def count_objects(cls):
        return cls.objects.count()    
    
    def __str__(self):
        return self.title
        


#########################  Tag  ################################

class Tag(models.Model):
    name = models.CharField(max_length=50)
    projects = models.ManyToManyField(Project, related_name='tags')

    @classmethod
    def count_objects(cls):
        return cls.objects.count()
    
    def __str__(self):
        return self.name

############################  Donation  ####################################################

class Donation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    donated_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def count_objects(cls):
        return cls.objects.count() 
    

#################################   Comment  ################################################

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return self.text

    @classmethod
    def count_objects(cls):
        return cls.objects.count()
    
    def __str__(self):
        return self.text
    
    

#################################   Reply   #################################################

class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


    @classmethod
    def count_objects(cls):
        return cls.objects.count()  

    def __str__(self):
        return self.text

###########################    ProjectCancellation    ################################

class ProjectCancellation(models.Model):
    project = models.OneToOneField(Project, on_delete=models.CASCADE)
    cancellation_reason = models.TextField()
    cancelled_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def count_objects(cls):
        return cls.objects.count()
    
    def __str__(self):
        return f"Cancellation of project: {self.project.title}"


##########################   Rating   #########################################    

class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    rating = models.IntegerField()

    def _str_(self):
        return f"{self.user.username} - {self.project.title}: {self.rating}"
    
    @classmethod
    def count_objects(cls):
        return cls.objects.count()
    
    @classmethod
    def average_rating(cls, project):
        all_ratings = cls.objects.filter(project=project)
        total_rating = sum(rating.rating for rating in all_ratings)
        
        if all_ratings.exists():
            average_rating = (total_rating / all_ratings.count()) * 20  
        else:
            average_rating = 0
        
        return average_rating
    
    
##############################  Report   ####################################    

class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
    reason = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    REPORT_CHOICES = (
        ('spam', 'Spam or scam'),
        ('inappropriate', 'Inappropriate content'),
        ('other', 'Other'),
    )

    def _str_(self):
        return f"Report by {self.user.username} on {self.created_at}"
    
    @classmethod
    def count_objects(cls):
        return cls.objects.count()
    
    

########################## Project Picture ####################################

class ProjectPicture(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='project_pictures/%Y/%m/%d')
 
    @classmethod
    def count_objects(cls):
        return cls.objects.count()
    
    def __str__(self):
        return f"Picture of project: {self.project.title}"

########################### featured projects#####################################

class FeaturedProject(models.Model):
    project = models.OneToOneField(Project, on_delete=models.CASCADE, related_name='featured_project')
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)

    @staticmethod
    def newest_featured_projects():
        return FeaturedProject.objects.filter(is_featured=True).order_by('-created_at')[:5]

    @classmethod
    def count_objects(cls):
        return cls.objects.count()
    
    def __str__(self):
        return f"Featured project: {self.project.title}"

admin_panel/templates/category/add_category_form.html
{% extends 'base_admin.html' %}

{% block content %}
<div class="container-fluid d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title text-center mb-2 ">Add Category</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_name" class="form-label">Name</label>
                            <input type="text" name="name" class="form-control" id="id_name" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Add Category</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

admin_panel/templates/category/category.html
{% extends 'base_admin.html' %}
{% block button %}
<div class="d-flex justify-content-start mb-3">
    <a href="{% url 'admin_panel:add_category' %}" class="btn btn-success me-2">Add Category</a>
</div>

{% endblock %}
{% block content %}
<div class="container-fluid d-flex justify-content-center align-items-center d-block" style="height: 100vh;">
    <div class="row">
        <div class="col-md-10">
            <h2 class="mb-4 text-center">Category Management</h2>
            <div style="height: 80vh; overflow-y: auto;"> 
                <table class="table table-striped table-bordered"> 
                    <thead class="text-white" style="background-color: rgb(0, 200, 255);">
                        <tr>
                            <th style="width: 100%;">Name</th> 
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for category in categories %}
                        <tr>
                            <td style="width: 100%;">{{ category.name }}</td> 
                            <td class="d-flex justify-content-between">
                                <a href="{% url 'admin_panel:update_category' category.id %}" class="btn btn-primary btn-sm me-2">Update</a>
                                <form action="{% url 'admin_panel:delete_category' category.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

admin_panel/templates/category/update_category.html
{% extends 'base_admin.html' %}

{% block content %}
<div class="container-fluid d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title text-center mb-0">Update Category</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_name" class="form-label">Name</label>
                            {{ form.name }}
                            {% if form.name.errors %}
                                <div class="invalid-feedback d-block">
                                    {% for error in form.name.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}