account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.login_view, name='login'),
    path('logout/', views.login_view, name='logout'),  # Use the custom logout view
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(extra_context={'next_page': '/home'}), name='password_reset_complete'),
    path('profile/',views.user_profile, name='profile'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('delete-account/', views.delete_account, name='delete_account'),
   
    
]

charityProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('project/', include('project.urls')), 
    path('admin_panel/', include('admin_panel.urls')),
    path('userPayment/', include('userPayment.urls')), 
    path('', include('paypal.standard.ipn.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('category/<int:category_id>/', views.category_detail, name='category_detail'),
    path('create/', views.create_project, name='create_project'),
    path('search/', views.search_projects, name='search_projects'),
    path('report/project',views.report_project, name='report_project'),
    path('project/<int:project_id>/', views.view_project, name='view_project'),
    path('submit_comment/', views.submit_comment, name='submit_comment'),
    path('add_rate/', views.add_rate, name='add_rate'),
    path('report/',views.report_comment, name='report_comment'),
    path('report/project',views.report_project, name='report_project'),
    path('project/<int:project_id>/cancel/', views.cancel_project, name='cancel_project'),
    path('appView/', views.app_view, name="appView"),
    path('donation/',views.payment_successful, name='donation-success'),
]

account/forms.py
import re
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from project.models import UserProfile
from django.core.validators import RegexValidator

class MixedAlphaNumericValidator:
    def __init__(self, message=None):
        self.message = message or 'Field must contain both letters and numbers.'

    def __call__(self, value):
        if not re.search(r'[a-zA-Z]', value) or not re.search(r'[0-9]', value):
            raise ValidationError(self.message)

mixed_alphanumeric_validator = MixedAlphaNumericValidator()

def validate_egyptian_mobile_number(value):
    if not re.match(r'^01[0-2]{1}[0-9]{8}$', value):
        raise ValidationError('Please enter a valid Egyptian mobile number.')

class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    
class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(validators=[mixed_alphanumeric_validator])
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if not first_name.isalpha():
            raise forms.ValidationError("First name must contain only letters.")
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if not last_name.isalpha():
            raise forms.ValidationError("Last name must contain only letters.")
        return last_name

class UserProfileRegistrationForm(forms.ModelForm):
    mobile_phone = forms.CharField(max_length=15, validators=[validate_egyptian_mobile_number])
    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ['mobile_phone', 'profile_picture']

egyptian_phone_validator = RegexValidator(
    regex=r'^01[0-9]{9}$',
    message='Please enter a valid Egyptian mobile phone number.'
)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [ 'username','first_name', 'last_name']
        
class UserProfileForm(forms.ModelForm):
    mobile_phone = forms.CharField(max_length=11, validators=[egyptian_phone_validator])
    country = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ['mobile_phone', 'profile_picture', 'birthdate', 'facebook_profile', 'country']

    def clean_country(self):
        country = self.cleaned_data.get('country')
        if not country.isalpha():
            raise forms.ValidationError("Country must contain only letters.")
        return country

account/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout, authenticate
from django.shortcuts import get_object_or_404, render, redirect
from admin_panel.forms import UserForm
from .forms import *
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required
from project.models import *
from django.contrib.auth.hashers import check_password
from django.urls import reverse
from datetime import datetime, timedelta
from django.utils import timezone
from django.utils.http import urlsafe_base64_decode
from django.http import HttpResponse



def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                return render(request, 'registration/login.html', {'form': form, 'error_message': 'Invalid email or password.'})
        
            if check_password(password, user.password):
                request.session['user_id'] = user.pk
                if user.is_superuser:
                    return redirect('admin_panel:admin_panel')  
                else:
                    return redirect('project:home')  
            else:
                return render(request, 'registration/login.html', {'form': form, 'error_message': 'Invalid email or password.'})
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})



def logout_view(request):
    if request.method == 'POST':
        auth_logout(request)
        request.session.flush()
        return HttpResponseRedirect(reverse('account:login'))
    else:
        return HttpResponseRedirect(reverse('account:login'))
    



def register(request):
    expires = request.GET.get('expires')  
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = UserProfileRegistrationForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            email = user_form.cleaned_data.get('email')
            if User.objects.filter(email=email).exists():
                user_form.add_error('email', 'This email is already in use. Please choose another one.')
            else:
                user = user_form.save()
                profile = profile_form.save(commit=False)
                profile.user = user
                profile.save()

                uid = urlsafe_base64_encode(user.pk.to_bytes(4, 'big'))
                token = default_token_generator.make_token(user)

                expiration_time = timezone.now() + timedelta(hours=24)

                protocol = 'http'
                domain = request.META['HTTP_HOST']
                activation_link = f"{protocol}://{domain}/?uidb64={uid}&token={token}&expires={expiration_time.timestamp()}"


                context = {
                    'email': user.email,
                    'protocol': protocol,
                    'domain': domain,
                    'uid': uid,
                    'token': token,
                    'user': user,
                    'activation_link': activation_link,
                }

                send_mail(
                    'Activate your account',
                    'registration/activation_email.html',
                    settings.EMAIL_HOST_USER,
                    [user.email],
                    fail_silently=False,
                    html_message=render_to_string('registration/activation_register.html', context)
                )

                return render(request, 'registration/activation_email_sent.html')
    else:
        user_form = UserRegistrationForm()
        profile_form = UserProfileRegistrationForm()

    if expires:
        expiration_time = datetime.fromtimestamp(float(expires))
        if expiration_time < timezone.now():
             return HttpResponse() 

    return render(request, 'registration/register.html', {'user_form': user_form, 'profile_form': profile_form})



def user_profile(request):
    user_id = request.session.get('user_id')
    if not user_id:
        return HttpResponse("User not logged in.")

    user = get_object_or_404(User, pk=user_id)
    user_profile = get_object_or_404(UserProfile, user=user)

    projects = Project.objects.filter(creator=user)
    donations = Donation.objects.filter(user=user)

    context = {
        'user_profile': user_profile,
        'projects': projects,
        'donations': donations,
    }
    return render(request, 'profile/Profile.html', context)




def delete_account(request):
    error_message = None  
    
    if request.method == 'POST':
        password = request.POST.get('password', '')
        user = authenticate(username=request.user.username, password=password)
        if user is not None:
            user_profile = UserProfile.objects.get(user=user)
            user_profile.delete()
            user.delete()
            auth_logout(request)
            request.session.pop('user_id', None)  
            return redirect('account:register') 
        else:
            error_message = 'Invalid password. Please try again.'
  
    return render(request, 'profile/delete_account.html', {'error_message': error_message})



def update_user(request, user_id):
    user = User.objects.get(pk=user_id)
    profile, created = UserProfile.objects.get_or_create(user=user)

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=profile)
        
        if user_form.is_valid() and profile_form.is_valid():
            updated_user = user_form.save()
            profile_form.save()

            return redirect('account:profile')  
    else:
        user_form = UserForm(instance=user)
        profile_form = UserProfileForm(instance=profile)
        
    return render(request, 'profile/userUpdate.html', {'user_form': user_form, 'profile_form': profile_form})

account/templates/profile/delete_account.html
{% extends 'base.html' %}

{% block title %} Delete Account {% endblock title %}

{% block content %}
<section>
  <div class="container">
    <div class="py-5 mx-auto">
      <div class="col-md-6 card d-flex shadow-lg p-4 mt-5 mx-auto">
        <div class="text-center">
          <h3 class="font-weight-bolder">Delete Account</h3>
          <p>Are you sure you want to delete your account?</p>
        </div>
        {% if error_message %}
        <div class="alert alert-danger" role="alert">
          {{ error_message }}
        </div>
        {% endif %}
        <form method="post" action="{% url 'account:delete_account' %}">
          {% csrf_token %}
          <div class="mb-3">
            <label class="form-label">Password</label>
            <input type="password" name="password" class="form-control" placeholder="Enter your password" required>
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-lg bg-gradient-danger btn-lg w-100 mt-4 mb-0">Delete Account</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

account/templates/profile/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} User Profile {% endblock title %}

{% block content %}
<div id="user-profile" class="container my-md-5 py-5">
    <div class="row">
        <!-- left panel -->
        <div class="col-md-3 profile-nav shadow-lg ps-0 ">
            {% if user_profile.profile_picture and user_profile.profile_picture.url %}
                <div class="user-heading bg-gradient-primary text-white text-center py-4">
                    <img src="{{ user_profile.profile_picture.url }}" class="card-img-top border border-2 rounded-circle my-3"
                        alt="profile img" style="width: 150px; height:150px;">
                </div>
            {% else %}
                <div class="user-heading bg-gradient-primary text-white text-center py-4">
                    <img src="{% static 'image/icon-3.png' %}" class="card-img-top border border-2 rounded-circle my-3"
                        alt="default profile img" style="width: 150px; height:150px;">
                </div>
            {% endif %}

            <ul class="nav flex-column bg-white shadow-lg py-3 my-md-0 my-5 mx-2">
                <li class="text-center">
                    <h4 class="font-weight-bolder mt-2">{{ user_profile.user.first_name|title }} {{ user_profile.user.last_name|title }}</h4>
                </li>

                <li class="text-center">
                    <p class="text-sm"><i class="fa-regular fa-user" style="color: #e24a18;"></i>{{ user_profile.user.username }}</p>  
                </li>

                <li class="text-center">
                    <p class="text-sm"> <i class="fa-regular fa-envelope" style="color: #e24a18;"></i> {{ user_profile.user.email }}</p>
                </li>
                <hr>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:update_user' user_profile.user.id %}"><i class="fas fa-user-edit me-2"></i>Edit Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:delete_account' %}"><i class="fas fa-user-slash me-2"></i>Delete Account</a>
                </li>
            </ul>
        </div>

        <!-- right panel -->
        <div class="col-md-9">
            <div class="row">
                <!-- User Details -->
                <div class="col-md-12">
                    <div class="profile-info shadow-lg bg-white rounded px-5 py-4 mb-4">
                        <h3 class="mb-4">Your Info</h3>
                        <div class="row">
                            <div class="col-md-6">
                                <p><strong>First Name:</strong> {{ user_profile.user.first_name|title }}</p>
                                <p><strong>Last Name:</strong> {{ user_profile.user.last_name|title }}</p>
                                {% if user_profile.country %}
                                    <p><strong>Country:</strong> {{ user_profile.country|title }}</p>
                                {% endif %}
                                {% if user_profile.birthdate %}
                                    <p><strong>Birthday:</strong> {{ user_profile.birthdate|date:"F d, Y" }}</p>
                                {% endif %}
                                {% if user_profile.facebook_profile %}
                                    <p><strong>Facebook Profile:</strong> {{ user_profile.facebook_profile }}</p>
                                {% endif %}
                            </div>
                            <div class="col-md-6">
                                <p><strong>Email:</strong> {{ user_profile.user.email }}</p>
                                <p><strong>Mobile:</strong> {{ user_profile.mobile_phone }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="bg-white rounded px-4 py-4 mb-4 shadow-lg">
                        <h5 class="mb-3"><i class="fas fa-coins text-primary me-2"></i>Donations</h5>
                        <h4 class="mb-0">{{ donations|length }}</h4>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="bg-white rounded px-4 py-4 mb-4 shadow-lg">
                        <h5 class="mb-3"><i class="fas fa-chart-pie text-primary me-2"></i>Projects</h5>
                        <h4 class="mb-0">{{ projects|length }}</h4>
                    </div>
                </div>
            </div>

            <!-- Table -->
            <div class="row">
                <div class="col-md-12">
                    <div class="bg-white rounded px-5 py-4 mb-4 shadow-lg">
                        <h3 class="mb-4">Your Donations</h3>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">Title</th>
                                    <th scope="col">Donation</th>
                                    <th scope="col">Created at</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if donations %}
                                    {% for donation in donations %}
                                        <tr>
                                            <td>{{ donation.project.title|truncatewords:2 }}</td>
                                            <td>{{ donation.amount }} L.E</td>
                                            <td>{{ donation.donated_at|date:"F d, Y" }}</td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr><td colspan="3">You haven't donated to any project yet :</td></tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Projects -->
            <div class="row">
                <div class="col-md-12">
                    <h3 class="mb-4">Your Projects</h3>
                    <div class="row">
                        {% for project in projects %}
                            {% if not project.is_cancelled %}  <!-- Add this condition -->
                                <div class="col-md-4">
                                    <div class="card nearbyCard ratecard mb-4">
                                        <img src="{{ project.pictures }}" class="card-img-top" alt="{{ project.title }}">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ project.title|title }}</h5>
                                            <p class="card-text">{{ project.details|truncatewords:20 }}</p>
                                            <p class="card-text">Raised: ${{ project.total_donations }} /${{ project.total_target }}</p>
                                            <div class="loader-container">
                                                <div class="loader loader-progress" data-progress="{{ project.progress_percentage }}">0%</div>               
                                            </div>
                                            <br>
                                            <!-- Add Cancel button -->
                                            <form action="{% url 'project:cancel_project' project.id %}" method="post">
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-danger">Cancel</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block additional_js %}
<script src="{% static 'js/homeStyle.js' %}"></script>
{% endblock %}

account/templates/profile/userUpdate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5 my-5">
    <div class="row my-5">
        <div class="col-md-8 offset-md-2 ">
            <div class="card shadow  my-5">
                <div class="card-body">
                    <h2 class=" update text-center mb-4 text-light">Update Your Informations</h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in user_form %}
                            <div class="mb-3">
                                <label class="form-label fw-bold">{{ field.label_tag }}</label>
                                {{ field }}
                                {% if field.errors %}
                                    <div class="invalid-feedback d-block">
                                        {% for error in field.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        {% for field in profile_form %}
                            <div class="mb-3">
                                <label class="form-label fw-bold">{{ field.label_tag }}</label>
                                {{ field }}
                                {% if field.errors %}
                                    <div class="invalid-feedback d-block">
                                        {% for error in field.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="text-center">
                            <button type="submit" class="btn btn-warning rounded btn-update">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}