account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.login_view, name='login'),
    path('logout/', views.login_view, name='logout'),  # Use the custom logout view
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(extra_context={'next_page': '/home'}), name='password_reset_complete'),
    path('profile/',views.user_profile, name='profile'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('delete-account/', views.delete_account, name='delete_account'),
   
    
]

admin_panel/urls.py
from django.urls import path
from . import views

app_name = 'admin_panel'

urlpatterns = [
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    path('user_profile/', views.user_profile_view, name='user_profile'),
    path('delete_profile/<int:profile_id>/', views.delete_profile, name='delete_profile'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('add_user/', views.add_user, name='add_user'),
    path('categories/', views.category_list, name='category_list'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('update_category/<int:category_id>/', views.update_category, name='update_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('featured-projects/', views.featured_projects, name='featured_projects'),
    path('delete-featured-project/<int:project_id>/', views.delete_featured_project, name='delete_featured_project'),
    path('featured-projects/<int:project_id>/update/', views.update_featured_project, name='update_featured_project'),
    path('add_featured_project/', views.add_featured_project, name='add_featured_project'),
    path('comments/', views.comment_list, name='comment'),
    path('comments/add/', views.add_comment, name='addcomment'),
    path('comments/<int:pk>/update/', views.update_comment, name='updatecomment'),
    path('add_donation/', views.add_donation, name='add_donation'),
    path('update_donation/<int:donation_id>/', views.update_donation, name='update_donation'),
    path('list_donations/', views.list_donations, name='donations'),
    path('add_reply/', views.add_reply, name='add_reply'),
    path('update_reply/<int:reply_id>/', views.update_reply, name='update_reply'),
    path('list_replies/', views.list_replies, name='replies'),
    path('show-tags/', views.show_added_tags, name='show_added_tags'),
    path('add-tag/',views.add_tag, name='add_tag'),
    path('update-tag/<int:tag_id>/',views.update_tag, name='update_tag'),
    path('delete-tag/<int:tag_id>/', views.delete_tag, name='delete_tag'),
    path('rate-project/', views.rate_project, name='rate_project'),
    path('show-rate/', views.show_rate, name='show_rate'),
    path('update-rating/<int:rating_id>/', views.update_rating, name='update_rating'),
    path('delete-rating/<int:rating_id>/', views.delete_rating, name='delete_rating'),
    path('add-report/', views.add_report, name='add_report'),
    path('show-reports/', views.show_reports, name='show_reports'),
    path('update_report/<int:report_id>/', views.update_report, name='update_report'),
    path('delete_report/<int:report_id>/', views.delete_report, name='delete_report'),
    path('projects/', views.project_list_view, name='project'), 
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('update_project/<int:project_id>/', views.update_project, name='update_project'),
    path('add_project/', views.add_project, name='add_project'),
    path('cancellation/list/', views.cancellation_list, name='cancellation_list'),
    path('update_cancellation/<int:cancellation_id>/', views.update_cancellation, name='update_cancellation'),
    path('cancellation/create/', views.create_cancellation, name='create_cancellation'),
    path('cancellation/<int:cancellation_id>/delete/', views.delete_cancellation, name='delete_cancellation'),
    path('project/pictures/', views.project_picture_list, name='project_picture_list'),
    path('project/pictures/add/', views.add_project_picture, name='add_project_picture'),
    path('project/pictures/<int:picture_id>/update/', views.update_project_picture, name='update_project_picture'),
    path('project/pictures/<int:picture_id>/delete/', views.delete_project_picture, name='delete_project_picture'),

   
]

charityProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('project/', include('project.urls')), 
    path('admin_panel/', include('admin_panel.urls')),
    path('userPayment/', include('userPayment.urls')), 
    path('', include('paypal.standard.ipn.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_panel/models.py
from django.db import models

# Create your models here.

admin_panel/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .forms import *
from .models import *

def admin_panel(request):
    tables = [
        ('User Profile', UserProfile.count_objects()),
        ('Category', Category.count_objects()),
        ('Project', Project.count_objects()),
        ('Tag', Tag.count_objects()),
        ('Donation', Donation.count_objects()),
        ('Comment', Comment.count_objects()),
        ('Reply', Reply.count_objects()),
        ('Project Cancellation', ProjectCancellation.count_objects()),
        ('Rating', Rating.count_objects()),
        ('Report', Report.count_objects()),
        ('Project Picture', ProjectPicture.count_objects()),
        ('Featured Project', FeaturedProject.count_objects()),
    ]
    return render(request, 'home/home_admin.html', {'tables': tables})


def user_profile_view(request):
    user_profiles = UserProfile.objects.all()
    return render(request, 'user_profile/user_profile.html', {'user_profiles': user_profiles})

def delete_profile(request, profile_id):
    if request.method == 'POST':
        try:
            profile = UserProfile.objects.get(id=profile_id)
            user_id = profile.user.id
            User.objects.filter(id=user_id).delete()
            profile.delete()
        except UserProfile.DoesNotExist:
            pass  
    return redirect('admin_panel:user_profile')

def update_user(request, user_id):
    user = User.objects.get(pk=user_id)
    profile, created = UserProfile.objects.get_or_create(user=user)

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=profile)
        
        if user_form.is_valid() and profile_form.is_valid():
            email = user_form.cleaned_data.get('email')
            if User.objects.exclude(pk=user_id).filter(email=email).exists():
                user_form.add_error('email', 'This email is already in use. Please choose another one.')
            else:
                user_form.save()
                profile_form.save()
                return redirect('admin_panel:user_profile') 
    else:
        user_form = UserForm(instance=user)
        profile_form = UserProfileForm(instance=profile)
        
    return render(request, 'user_profile/user_update_form.html', {'user_form': user_form, 'profile_form': profile_form})

def add_user(request):
    if request.method == 'POST':
        user_form = AddUserForm(request.POST)
        profile_form = AddUserProfileForm(request.POST, request.FILES)  

        if user_form.is_valid() and profile_form.is_valid():
            email = user_form.cleaned_data.get('email')
            if User.objects.filter(email=email).exists():
                user_form.add_error('email', 'This email is already in use. Please choose another one.')
            else:
                user_instance = user_form.save(commit=False)
                user_instance.set_password(user_form.cleaned_data["password"])
                user_instance.save()

                profile_instance = profile_form.save(commit=False)
                profile_instance.user = user_instance
                
                if 'image' in request.FILES:
                    profile_instance.image = request.FILES['image']
                    
                profile_instance.save()
                
                return redirect('admin_panel:user_profile')
    else:
        user_form = AddUserForm()
        profile_form = AddUserProfileForm()
        
    return render(request, 'user_profile/add_user_form.html', {'user_form': user_form, 'profile_form': profile_form})

###################################category################################

def category_list(request):
    categories = Category.objects.all()
    return render(request, 'category/category.html', {'categories': categories})

def delete_category(request, category_id):
    if request.method == 'POST':
        try:
            category = Category.objects.get(id=category_id)
            category.delete()
        except Category.DoesNotExist:
            pass 
    return redirect('admin_panel:category_list')

def update_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    if request.method == 'POST':
        form = CategoryUpdateForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('admin_panel:category_list')
    else:
        form = CategoryUpdateForm(instance=category)
    return render(request, 'category/update_category.html', {'form': form})

def add_category(request):
    if request.method == 'POST':
        form = AddCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_panel:category_list') 
    else:
        form = AddCategoryForm()
    return render(request, 'category/add_category_form.html', {'form': form})


###################################featured project################################

def featured_projects(request):
    featured_projects = FeaturedProject.objects.all()
    return render(request, 'featured_project/featured_project.html', {'featured_projects': featured_projects})

def delete_featured_project(request, project_id):
    featured_project = FeaturedProject.objects.get(project_id=project_id)
    if request.method == 'POST':
        featured_project.delete()
        return redirect('admin_panel:featured_projects')
    return render(request, 'featured_project/featured_project.html', {'featured_projects': FeaturedProject.objects.all()})

def update_featured_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    featured_project = get_object_or_404(FeaturedProject, project=project)
    if request.method == 'POST':
        form = FeaturedProjectForm(request.POST, instance=featured_project)
        if form.is_valid():
            form.save()
            return redirect('admin_panel:featured_projects')
    else:
        form = FeaturedProjectForm(instance=featured_project)
    return render(request, 'featured_project/featured_project_update_form.html', {'form': form})

def add_featured_project(request):
    if request.method == 'POST':
        form = FeaturedProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_panel:featured_projects') 
    else:
        form = FeaturedProjectForm()
    return render(request, 'featured_project/add_featured_project.html', {'form': form})


###################################comment################################

def comment_list(request):
    comments = Comment.objects.all()
    if request.method == 'POST':
        comment_id = request.POST.get('comment_id')
        comment = get_object_or_404(Comment, pk=comment_id)
        comment.delete()
        return redirect('admin_panel:comment')
    return render(request, 'comment/comment.html', {'comments': comments})

def add_comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_panel:comment')
    else:
        form = CommentForm()
    return render(request, 'comment/addcomment.html', {'form': form})

def update_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:comment'))
    else:
        form = CommentForm(instance=comment)
    return render(request, 'comment/updatecomment.html', {'form': form, 'comment': comment})



###################################donations################################

def add_donation(request):
    if request.method == 'POST':
        form = DonationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_panel:donations')
    else:
        form = DonationForm()
    return render(request, 'donation/addDonations.html', {'form': form})

def update_donation(request, donation_id):
    donation = get_object_or_404(Donation, pk=donation_id)
    
    if request.method == 'POST':
        form = DonationForm(request.POST, instance=donation)
        if form.is_valid():
            form.save()
            return redirect('admin_panel:donations')
    else:
        form = DonationForm(instance=donation)
    
    return render(request, 'donation/updateDonations.html', {'form': form, 'donation': donation})

def list_donations(request):
    donations = Donation.objects.all()
    if request.method == 'POST':
        donation_id = request.POST.get('donation_id')
        donation = get_object_or_404(Donation , pk=donation_id)
        donation.delete()
        return redirect('admin_panel:donations')
    return render(request, 'donation/donations.html', {'donations': donations})



###################################reply################################

def add_reply(request):
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_panel:replies')
    else:
        form = ReplyForm()
    return render(request, 'reply/addReply.html', {'form': form})

def update_reply(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    
    if request.method == 'POST':
        form = ReplyForm(request.POST, instance=reply)

admin_panel/templates/user_profile/add_user_form.html
{% extends 'base_admin.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-header bg-primary text-white">
                    <h2 class="mb-0">Add New User</h2>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in user_form %}
                        <div class="mb-3">
                            <label class="form-label">{{ field.label_tag }}</label>
                            {{ field }}
                            {% if field.errors %}
                            <div class="invalid-feedback d-block">
                                {% for error in field.errors %}
                                {{ error }}
                                {% endfor %}
                            </div>
                            {% endif %}
                        </div>
                        {% endfor %}
                        {% for field in profile_form %}
                        <div class="mb-3">
                            <label class="form-label">{{ field.label_tag }}</label>
                            {{ field }}
                            {% if field.errors %}
                            <div class="invalid-feedback d-block">
                                {% for error in field.errors %}
                                {{ error }}
                                {% endfor %}
                            </div>
                            {% endif %}
                        </div>
                        {% endfor %}
                        {% if profile_form.confirm_password.errors %}
                        <div class="mb-3">
                            <div class="invalid-feedback d-block">
                                {% for error in profile_form.confirm_password.errors %}
                                {{ error }}
                                {% endfor %}
                            </div>
                        </div>
                        {% endif %}
                        <button type="submit" class="btn btn-primary">Add User</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

admin_panel/templates/user_profile/user_profile.html
{% extends 'base_admin.html' %}
{% load static %}
{% block button %}
<div class="d-flex justify-content-start mb-3">
    <a href="{% url 'admin_panel:add_user' %}" class="btn btn-success me-2">Add New User</a>
</div>

{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
           
            <h2>User Profiles</h2>
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead class="table"style=" background-color: rgb(0, 200, 255);">
                        <tr class="text-white">
                            <th>Username</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>email</th>
                            <th>Password</th>
                            <th>Mobile Phone</th>
                            <th>Profile Picture URL</th>
                            <th>Birthdate</th>
                            <th>Facebook Profile</th>
                            <th>Country</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for profile in user_profiles %}
                        <tr>
                            <td>{{ profile.user.username }}</td>
                            <td>{{ profile.user.first_name }}</td>
                            <td>{{ profile.user.last_name }}</td>
                            <td>{{ profile.user.email }}</td>
                            <td>*******</td>
                            <td>{{ profile.mobile_phone }}</td>
                            <td>
                                <ul>
                                    <li>{{ profile.profile_picture }}</li>
                                </ul>
                            </td>
                            <td>{{ profile.birthdate }}</td>
                            <td>{{ profile.facebook_profile }}</td>
                            <td>{{ profile.country }}</td>
                            <td>
                                <div class="d-flex">
                                    <a href="{% url 'admin_panel:update_user' user_id=profile.user.id %}" class="btn btn-primary me-2">Update</a>
                                    <form action="{% url 'admin_panel:delete_profile' profile.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

admin_panel/templates/user_profile/user_update_form.html
{% extends 'base_admin.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card shadow">
                <div class="card-header bg-primary text-white">
                    <h2 class="mb-0">Update User</h2>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in user_form %}
                            <div class="mb-3">
                                <label class="form-label">{{ field.label_tag }}</label>
                                {{ field }}
                                {% if field.errors %}
                                    <div class="invalid-feedback d-block">
                                        {% for error in field.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        {% for field in profile_form %}
                            <div class="mb-3">
                                <label class="form-label">{{ field.label_tag }}</label>
                                {{ field }}
                                {% if field.errors %}
                                    <div class="invalid-feedback d-block">
                                        {% for error in field.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary mt-3">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}